obj
	Dragonballs
		Savable=1
		Stealable=1
		Health=1.#INF
		icon='Dragonballs.dmi'
		Dragonball_1
			pixel_x=0
			pixel_y=0
		Dragonball_2
			pixel_x=-16
			pixel_y=-10
		Dragonball_3
			pixel_x=-0
			pixel_y=-16
		Dragonball_4
			pixel_x=16
			pixel_y=-10
		Dragonball_5
			pixel_x=-16
			pixel_y=10
		Dragonball_6
			pixel_x=0
			pixel_y=12
		Dragonball_7
			pixel_x=16
			pixel_y=10